### ISSUE TITLE
Can we get vehicle's heading info?

### ISSUE THREAD

**Issue by qiqiji** [nmullaney/candash#101]
BO_ 723 ID2D3UI_solarData: 8 ChassisBus
 SG_ UI_isSunUp : 25|2@1+ (1,0) [0|3] ""  Receiver
 SG_ UI_minsToSunrise : 56|8@1+ (10,0) [0|2550] "min"  Receiver
 SG_ UI_minsToSunset : 48|8@1+ (10,0) [0|2550] "min"  Receiver
 SG_ UI_screenPCBTemperature : 40|8@1- (0.5,40) [-20|100] "C"  Receiver
 SG_ UI_solarAzimuthAngle : 0|16@1- (1,0) [-32767|32767] "deg"  Receiver
 SG_ UI_solarAzimuthAngleCarRef : 16|9@1- (1,0) [-256|254] "deg"  Receiver
 SG_ UI_solarElevationAngle : 32|8@1- (1,0) [-128|126] "deg"  Receiver

Someone says UI_solarAzimuthAngle - UI_solarAzimuthAngleCarRef will be the vehicle's heading
https://www.teslaownersonline.com/threads/diagnostic-port-and-data-access.7502/page-105#post-349702

but i found those numbers continuous changes with nonsense, is ID2D3UI_solarData now has a multiplexor now?

**Comment by carleeno** [comment]
Try `UI_gpsVehicleSpeed` `UI_gpsVehicleHeading`, you should be able to get the heading directly from the chassis bus

I don't think the solarData is mux'd, at least on 2024.3.10 it's still giving sensible solar elevation.

Fyi canserver discord is a better place to ask about general can signals. Are you looking for heading info in candash itself? how are you wanting it displayed?

**Comment by qiqiji** [comment]
Thanks for the reply.
I try UI_gpsVehicleHeading first, but i get 511 all the time, i will do more test

BO_ 985 ID3D9UI_gpsVehicleSpeed: 8 ChassisBus
 SG_ UI_gpsVehicleHeading : 8|16@1+ (0.0078125,0) [0|511.992] "deg"  Receiver

When i try UI_solarAzimuthAngleCarRef and UI_solarAzimuthAngle ,they are continuous changes (within 3-4 numbers loop) so i suspect they are mux'd at first place.

Actually i'm not using canserver now, i'm developing some little fun project myself with two esp32 board (one for transmitter, one for the display unit), just like the roles canserver and candash to be. i use a round display so i think it's a good idea to add a north arrow as a simple compass when i'm driving.

I have been tormented by this question for several days. Maybe that I was too eager to find help, without considering that this might not be the best place to ask. If I have caused any inconvenience, I sincerely apologize.

I'll do more test and thank you again.

**Comment by carleeno** [comment]
It's not an inconvenience, but you will probably find more people to help you on the canserver discord: https://discord.gg/W2pMGkhdcy

There's also a candash discord: https://discord.gg/Wr5VQaGY9M

People love home-brew solutions, no worries at all.
