### ISSUE TITLE
Speedo value "sticks"

### ISSUE THREAD

**Issue by orcinus** [nmullaney/candash#13]
Tiny nitpick.
It appears like the speedometer retains the last value regardless of drive mode or car state.
E.g.

![Traveling without moving](https://i.imgur.com/2pbO50J.jpg)

It'd probably make sense to blank it when in park.

Repro case:
1) go into park
2) switch to mock server
3) switch back to real server
4) last mocked value stays on the screen (because there's no speedo signal on the bus)

**Comment by osunick** [comment]
Yeah, this is because the display updates on change, because latency is not guaranteed i'd rather it be a real time display of vehicle state rather than worry about running timers to determine if the canserver is connected. Also, much less of an issue now that we have the screen blanking with LOS
