### ISSUE TITLE
Keep screen on

### ISSUE THREAD

**Issue by vekexasia** [nmullaney/candash#6]
I'm using a custom mount with no power cord to try rthis out.

I would suggest to use android:keepScreenOn="true" on the https://github.com/osunick/candash/blob/main/android/app/src/main/res/layout/activity_fullscreen.xml 

Since most people would not want their screen to turn off if the app is open. 

Alternatively if you feel someone would not want this feature it could be a new pref in the settings allowing the end-user to eventually decide if they want or not the flag toggled.

**Comment by osunick** [comment]
The main reason it behaves this way is so that it will power down when the
car sleeps, as my goal was an experience that didn't need any interaction
if you wanted to leave it alone, and I'll think about changing this
behavior when I do feature work again, but as a non default pref.

**Comment by vekexasia** [comment]
It could also work this way. If car is in "P" then setscreenalwayson to
false. If car is in drive then set it to true?

Il sab 19 feb 2022, 19:20 Nick Nguyen ***@***.***> ha scritto:

> The main reason it behaves this way is so that it will power down when the
> car sleeps, as my goal was an experience that didn't need any interaction
> if you wanted to leave it alone, and I'll think about changing this
> behavior when I do feature work again, but as a non default pref.
>

**Comment by osunick** [comment]
That's a really good idea. I'll implement that it a bit.

**Comment by osunick** [comment]
Closed because @carleeno implemented a better version of this idea.
